FROM python:3.9-slim

WORKDIR /mlops_team

# requirements.txt 먼저 복사
COPY requirements.txt /mlops_team/requirements.txt

RUN apt-get update && apt-get install -y \
    build-essential \
    libgomp1 \
    libomp-dev \
    curl \
    git

COPY . /mlops_team/


RUN pip install --no-cache-dir -r /mlops_team/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]